# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'SenseEar-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SenseEar-Project
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'PDFNet', podspec: 'https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec'
  
  target 'SenseEar-ProjectTests' do
    inherit! :search_paths
    pod 'Firebase'
    pod 'Nimble'
  end

end
